### ISSUE TITLE
pd_to_psql: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by yershovkiril** [d6t/d6tstack#11]
https://github.com/d6t/d6tstack/blob/155e9b9cfd74096667c93286b2c6042b74ecd008/d6tstack/utils.py#L69

The method `pd_to_psql ` has default value `None` for `schema_name` parameter, but in last update to v0.1.7 was added param to lower case statement. So, it breaks execution and has logical conflict.

**Comment by d6tdev** [comment]
fixed in v0.1.8 thanks for reporting
